[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "e808c2260c2d4628aa7eea21d96b8dd3536f6126"
libgfortran_version = "5.0.0"
os = "macos"

    [[SDPLR.download]]
    sha256 = "f6f19af7628663e85d60174adc8c2404f3b2001707e17f4061f9f5f6bc6a2186"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "77f2b00a5d466c77722e45b85b76ee884ece95bf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "7c7362cdf751f94a1bcab0b11e6b68ab12535be2ead3803f0b3d352822d493ea"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "764f3cf317ccfb06b4b48526dccff9b51e31291d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "b92d73261297de22cf4861e383e2bcca2d0ceb4382b9f6ae77cc4a06c33b5997"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "87c17bfa3779a1fd1344306b5928d3aaebf6e2e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "d69ce1a234deb839f78a46e8ff80b727edbedd401e8ddf3374f195a3271762a9"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "7fc57c96c6d3ea33221e8331bc3a61f2161c428e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "a05e991aa4231210c14edda167591198cbf4c5c0f3911e88b77622a0ac2316ba"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-musl-libgfortran3.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "a7d0cdf131944fc1ef12d5ccebbfa2d8778eac1d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "f0fe3572ae32e5dadb7fa606935020a7803705b6d98ed56be63e3b96eb7584c6"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-musl-libgfortran4.tar.gz"
[[SDPLR]]
arch = "aarch64"
git-tree-sha1 = "7fa095b1d4cb54f3f2191b9053dfdb3208a7068d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "e8e10e1e8b6e7324f28134d2e46c74f3c1e14cb35ddb701e4ce0f943b08f757a"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.aarch64-linux-musl-libgfortran5.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7b8f493a7f997bab9143a006723b038e2771ed7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "89825571da8c133ddeb0e05bc8eadc83b0138a9746e9938eb65c828557f58d3e"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2450c74c56a5d5bf7bb6bf566f6311de685105ad"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "afeef87be7a7347ef9a2be17a8790a6bd86b395a3c8119fa94ea05f4ee7e7944"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ddb1e584fada442617ddb48b334459e58f5bce35"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "98f11669ee04108c83bc0258a50697b954b1ae88367c755953fe334f697b02e6"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "798dcba54db7be49a4452e0542e1662bd80d78ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "5eaa3e05793fa7515350c7396f88be615f07feb2a28810f802594c7e5fdf593e"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57a96fbe3ad47a957b80fb5748ce6701e81bd371"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "6553126de0048c4028dfa4145bde04772c655fc02bf692a0c4d42aeebd119e89"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SDPLR]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "306a8a6830b6eaf8bc830e2f65b97ebe3b6cca82"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "0afb7465eac854e30ec074fb40537c300148c2fcc68d79eb708206562cabd08a"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d59dd88651511d6e713086b5af6e84b6b906c97"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "f03bbb03bb1929c46e31cec4e5dc3e0b866e41ffd6f458e43826bf0bbb25e075"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5dca44c18f3565d9c1fba5e07a650e99aa83fe4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "0ed075eb5e2907394259b1f0efbe4d0ad48d1887722497405643c0324a89be0a"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "90040738090f755a0d8f63a5e9915cbfe1c5e420"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "18816a7f266973ff3fbe9e10d02ee1e929cc9350b7feda5919dc2d69bf5a8120"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c563968ad73f1186519ac8472aee8c441a2baa7f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "b5cfcbd20b4943741e3279bc95081d5f1ef2460df15abe0bf2df955a5d017da4"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "93eb71be7957cb54d0e2c5c14b60a5de58b43820"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "1f46085dcfbf1311b29e70958b36f412a7d585bc24aac00f3c3bd5e27f4150f3"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SDPLR]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "301fc63b63d064f3b0a844e2f5714428ee31b104"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "39d5660d1ccbfbdd6fa9121e7c548b0b43e9f9c92a3e77c2e5b5defbbf7ad7e6"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "e267f0a96abe98c7eea4c4b0746760945987e9e9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "b7b00c9a922d4acc45a85c29a95e612a68cd26e4e7bdf7f6b5ba5e3981f5cb24"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-gnu-libgfortran3.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "fe5fa287ab547fc8c1534b7a054f4e23cdcf5009"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "91aa51b2a147c2c1cfac2b4915c06437b0aac2f2811596eedba31173dd59d9f1"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-gnu-libgfortran4.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "72d51f3deae158ee1a193f99c544cad84a473951"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "f246459c1459bbae73d2b51ea6347cb42ab9ae524ce961c722bf421c4e5977f5"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-gnu-libgfortran5.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "2630d8255f2f1fd1c91143e82ae1c0feb3367cc2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "9ee2951aff82f6c48d6efea815a06f09dead041cc7278898b623031794aedfce"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-musl-libgfortran3.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "c71120b9d4b0a279d84d39a7afcbd2e6692d6295"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "31828189c4b00d5c553f192febfe98c2a0b3c1424ec7dc372c5566962bc7dfa2"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-musl-libgfortran4.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "039d479944b04f8a67813117d4099f9e643591f5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "19b11b65f8ce7fde7c614da3304c759ff38044888c622eeea7b9a32774f4328c"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-linux-musl-libgfortran5.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "5c56aac40c8a0ca0397ea86c7b64f0bccbcf2f94"
libgfortran_version = "3.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "7dfa537f03bf3aada244844f33e123252cf6d979168c0a13bf044bcd84d30040"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-w64-mingw32-libgfortran3.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "6b6f6e4b24cb637e98bdf61461a8b7836e6010fc"
libgfortran_version = "4.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "e46b063a31bd7db2c89f635b1c8c62a3dee5d89da8d5933cba6b336c3456df53"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-w64-mingw32-libgfortran4.tar.gz"
[[SDPLR]]
arch = "i686"
git-tree-sha1 = "4aa7d73932e0151ec91ceb1d668c79e7f20ff9a2"
libgfortran_version = "5.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "9a1f0e04a51ad9093270ff26f7e85e03a6749a23b1f76ff9eef68eedc32924c9"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.i686-w64-mingw32-libgfortran5.tar.gz"
[[SDPLR]]
arch = "powerpc64le"
git-tree-sha1 = "ac13e183100f2614461cc0b4aace6237c4569fb0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "37c556ca8daf6b05f7206517cadf1efdf05236c4c83f6b84ca46d251e86b7706"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SDPLR]]
arch = "powerpc64le"
git-tree-sha1 = "602e46e58924cfc6b41771c4898d8e069b28a6ad"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "6142e5b22e6e1d560d83e1bc10eccebb27e9fefb8f89b8d43fd64095b00735b3"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SDPLR]]
arch = "powerpc64le"
git-tree-sha1 = "3663bba3039980c6d25e3d7fbd0c2b6470788b69"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "d6275dc467c07814db175f1c5071f34e86786cf7463c3ff6af2c523ce552653c"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "8e167d06b97cee1a1b0a2568cb29465b27b04343"
libgfortran_version = "3.0.0"
os = "macos"

    [[SDPLR.download]]
    sha256 = "cdb82c7f3d7d6178ab31282c681b40fa8fa3c617ceac2f6a7106f4214ac0ac78"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "179b079a80c5ab2ec74e9316549b71c674469c24"
libgfortran_version = "4.0.0"
os = "macos"

    [[SDPLR.download]]
    sha256 = "0a3946537ec9d316c5fce9951f2842a476f75ed5e30e8e9db07529c4ab7b217f"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "469dc700a644c27a8e615da778bf515d3c04812d"
libgfortran_version = "5.0.0"
os = "macos"

    [[SDPLR.download]]
    sha256 = "2873e5e9de67a729348827d7779f963172e862b4cc837a152e5a8490e50007dd"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "c514df13b37bb2fad59371663fa1d7d678950131"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "9b781a13c2a7380fcf25ea942956e67c672218a4f201c80dcd3c82dd3aafb4b7"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "75050f7b87076d59689fc2c36b1208d5f8fa750d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "f3d3206827dc77d41a4776cafd102be16730832959f75bc206337f7c5814899a"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "810bc62e667bb658b8a84452955ed02d8c0f4807"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "defca0b1cae876b4cd6e48609840435de7d3e20a6615f0ca580dc549ba874c20"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "4e95783c7df59f890832217e7e4a0e9e1a7fce2b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "881aeb9e6c0dfda29ebdfc7295880d256b591df4930c1a815dc658ffed517545"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-musl-libgfortran3.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "08b4ffcccf03a317d045c9436b838a0ae3f2397c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "defce671e4eac26d133edade5a92c54cad09949ede0f57c321d88ee0cefc4101"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-musl-libgfortran4.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "294c63bf0a7cc4d5ed6b71e3f89613827ac72055"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SDPLR.download]]
    sha256 = "90ee83b82a182c3693ce964178e2171ba6786c627afc84cd729f58e7b13b7eed"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-linux-musl-libgfortran5.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "fa7a7ed0c0aad94b7b9c21c8b1d34d8b3e0ef57d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SDPLR.download]]
    sha256 = "ae62abb842846ac8b35c14c26ffc6e47c6caecbed82a9d31342b4cbe008b6c2e"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "9ae88d5ad7dda060fed8e8b0c58ddfb1215d95ef"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SDPLR.download]]
    sha256 = "fd352e1cc94106a44b2a47ed41e983d897a777894348aeb8ddec6d450b90dccc"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "940b3c880433a98ca5420983bb60040c2b686291"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SDPLR.download]]
    sha256 = "cfcd38d4464b65a9fd77838c6c6d14535f51656a76538b1fd6146e6f54097b2b"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "0ee08f74049c4adc352baacd3e58ad58874bae2b"
libgfortran_version = "3.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "9c48410cafbbf7e9d59571281505273bf3646f1994c7b0f46a5e12308e35b07b"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "4b5dd9c78351c755dd9b408429a21b0215419489"
libgfortran_version = "4.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "461c172820de14136e41f0226b28e703849dd1b69f64670347dd6a17b017533b"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SDPLR]]
arch = "x86_64"
git-tree-sha1 = "098d0f444968ef9c0e3262eb91609318a4245a69"
libgfortran_version = "5.0.0"
os = "windows"

    [[SDPLR.download]]
    sha256 = "c5e8b1ea8fc7f07fc8a6ff3271c3672ffe88b73af2853fbc8f7211a1972d41c4"
    url = "https://github.com/JuliaBinaryWrappers/SDPLR_jll.jl/releases/download/SDPLR-v100.1.300+0/SDPLR.v100.1.300.x86_64-w64-mingw32-libgfortran5.tar.gz"
