# Autogenerated wrapper script for SDPLR_jll for i686-w64-mingw32-libgfortran4
export libsdplr, sdplr

using OpenBLAS32_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("SDPLR")
JLLWrappers.@declare_library_product(libsdplr, "libsdplr.dll")
JLLWrappers.@declare_executable_product(sdplr)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libsdplr,
        "bin\\libsdplr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        sdplr,
        "bin\\sdplr.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
